import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";



const inter = Inter({ subsets: ["latin"] });
const { userId } = auth()
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Provider children={children}/></body>
    </html>
    </ClerkProvider>
  );
}
